### ISSUE TITLE
Visa backend configuration for Windows 

### ISSUE THREAD

**Issue by ozumana** [OE-FET/keithley2600#14]
Hi @SamSchott,
This is not an issue, but a usage noob question... 
How do I go about  setting up the backend visa configuration for windows (Win10, Python 3.8)? 
I am seeking to use the NI visa library already installed in my system.
Cheers,
G

**Comment by SamSchott** [comment]
Hi @ozumana,

This is a valid question and currently not well documented.

You can pass a keyword argument `visa_library` to the `Keithley2600` constructor to specify the backend. For example:

```python
from  keithley2600 import Keithley2600
k = Keithley2600('TCPIP0::192.168.2.121::INSTR', visa_library='path/to/library')
```

It defaults to using the PyVISA-py backend, selected by `visa_library='@py'`. But if you pass an empty string, it will use an installed IVI library (such as NI-VISA) if it can find one in standard locations and fall back to PyVISA-py otherwise.

You can find more information about selecting the backend in the [PyVISA docs](https://pyvisa.readthedocs.io/en/latest/introduction/configuring.html).

Hope this helps,
Sam

**Comment by ozumana** [comment]
Brilliant @SamSchott ! Thanks!
